version: "3.7"
services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: ebubekir
      MYSQL_PASSWORD: PASSWORD
    networks:
      - bookstore

  myapp:
    image: bookstore-api:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - bookstore  

networks:
  bookstore:
    driver: bridge #default oldugundan yazmaya gerek yok.
  